cat > docker-tcp.socket << EOL
[Unit]
Description=Docker Socket for the API

[Socket]
ListenStream=2375
BindIPv6Only=both
Service=docker.service

[Install]
WantedBy=sockets.target

EOL

sudo cp docker-tcp.socket /etc/systemd/system/docker-tcp.socket
sudo systemctl enable docker-tcp.socket
sudo systemctl stop docker
sudo systemctl start docker-tcp.socket
sudo systemctl start docker.socket
sudo systemctl start docker
